version: "3.7"
services:
  php:
    build:
      context: .
    volumes:
      - ..:/workspace
      - vscode-cache:/home/vscode/.vscode-server/extensions
    command: apache2-foreground
    ports:
      - 8888:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=x5vrvVQ7SP78XyvkSRJumJINLTLqQIW9
      - MYSQL_DATABASE=udev
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  mysql-data:
  vscode-cache:
